#ifndef MANUFACTURING_PROCESS_H
#define MANUFACTURING_PROCESS_H

void setup_manufacturing_process(void);

// Place and Transition enums
enum Places {
    P_RAW_MATERIAL,
    P_READY_TO_PROCESS,
    P_PROCESSING,
    P_PROCESSED,
    P_READY_TO_ASSEMBLE,
    P_ASSEMBLED,
    P_QUALITY_CHECK_1,
    P_POST_QC1_BUFFER,
    P_READY_FOR_INDIVIDUAL_PACKAGE,
    P_INDIVIDUALLY_PACKAGED,
    P_FINAL_PACKAGED,
    P_PAINTED,
    P_QUALITY_CHECK_2,
    P_WORKER,
    P_REWORK_BIN
};

enum Transitions {
    T_LOAD_MATERIAL,
    T_START_PROCESSING,
    T_FINISH_PROCESSING,
    T_START_ASSEMBLY,
    T_FINISH_ASSEMBLY,
    T_START_QC_1,
    T_PASS_QC_1,
    T_FAIL_QC_1,
    T_SELECT_TO_PAINT,
    T_SKIP_PAINT,
    T_START_QC_2,
    T_PASS_QC_2,
    T_FAIL_QC_2,
    T_INDIVIDUAL_PACKAGE,
    T_BULK_PACKAGE,
    T_REWORK_PROCESS
};

#endif // MANUFACTURING_PROCESS_H
